cache: cargo
language: rust
os:
  - linux
  - osx
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install xorg-dev; fi
script:
  - cargo build --verbose --lib
  - cargo build --verbose --example reference
  